syntax enable
set background=dark
colorscheme solarized

" jump to the last position when reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" load indentation rules and plugins according to the detected filetype.
if has("autocmd")
  filetype plugin indent on
endif

" Turn on line numbering. Turn it off with "set nonu"
set nu

" Case insensitive search
set ic

" Higlhight search
set hls

set autoindent   "Always set auto-indenting on"
set expandtab    "Insert spaces instead of tabs in insert mode. Use spaces for indents"
set tabstop=4    "Number of spaces that a <Tab> in the file counts for"
set shiftwidth=4 "Number of spaces to use for each step of (auto)indent"
set softtabstop=4

set incsearch        "postupne vyhledavani zapnuto
set ruler
set showcmd          "ukazuj, jake zadavam prikazy
set nowrap           "nezalamuj radky

set showmatch       " zapisete-li pravou závorku, ukáze vám k ní
set wildmenu        " doplnovanie ostavajucej casti mena v prikazovom rezime
"set mouse=a          "s mysi jde vse lepe :-)

if has("syntax")
  syntax on
  filetype on
  au BufNewFile,BufRead iptables.rules set filetype=iptables
endif"
